In [69]:
#Implement a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.
import numpy as np
def myVander(x, N, flag):
    listx=[]
    for i in x:
        list1=[]
        if(flag):
            list1 = [i**j for j in range(0,N,1)]
        else:
            list1 = [i**j for j in range(N-1,-1,-1)]
        listx.append(list1)
        
    return(listx) 

x = np.array([1, 2, 3, 5])
N = 4
print('Printing Alexandre-Theophile Vandermonde using myVander(x, N, True)')
retList = myVander(x, N, True)
print(retList)
print('Printing Alexandre-Theophile Vandermonde using built in function np.vander')
print(np.vander(x, N, True))
print("-----------------------------------------------------------------")
print('Printing Alexandre-Theophile Vandermonde using myVander(x, N, True)')
retList = myVander(x, N, False)
print(retList)
print('Printing Alexandre-Theophile Vandermonde using built in function np.vander')
print(np.vander(x, N, False))

Printing Alexandre-Theophile Vandermonde using myVander(x, N, True)
[[1, 1, 1, 1], [1, 2, 4, 8], [1, 3, 9, 27], [1, 5, 25, 125]]
Printing Alexandre-Theophile Vandermonde using built in function np.vander
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]
-----------------------------------------------------------------
Printing Alexandre-Theophile Vandermonde using myVander(x, N, True)
[[1, 1, 1, 1], [8, 4, 2, 1], [27, 9, 3, 1], [125, 25, 5, 1]]
Printing Alexandre-Theophile Vandermonde using built in function np.vander
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
